Admin account username: admin 
password: password


INSERT INTO usercredential
VALUES ('admin', 'password'),
  ('tharusha', '1234');


INSERT INTO rooms (RoomNo, CustName, RoomPackage, RoomType, Status)
VALUES (101, '', '', 'Single', 'Not Booked'),
  (102, '', '', 'Double', 'Not Booked'),
  (103, '', '', 'Triple', 'Not Booked'),
  (104, '', '', 'Quad', 'Not Booked'),
  (105, '', '', 'Queen', 'Not Booked'),
  (106, '', '', 'King', 'Not Booked'),
  (107, '', '', 'Twin', 'Not Booked'),
  (108, '', '', 'Hollywood Twin', 'Not Booked'),
  (109, '', '', 'Double-Double', 'Not Booked'),
  (110, '', '', 'Studio', 'Not Booked'),
  (111, '', '', 'Standard', 'Not Booked'),
  (112, '', '', 'Deluxe', 'Not Booked'),
  (113, '', '', 'Joint', 'Not Booked'),
  (114, '', '', 'Connecting', 'Not Booked'),
  (115, '', '', 'Suite', 'Not Booked'),
  (116, '', '', 'Standard', 'Not Booked'),
  (117, '', '', 'Apartment-Style', 'Not Booked'),
  (118, '', '', 'Accessible', 'Not Booked'),
  (119, '', '', 'Cabana', 'Not Booked'),
  (120, '', '', 'Villa', 'Not Booked'),
  (121, '', '', 'Single', 'Not Booked'),
  (122, '', '', 'Double', 'Not Booked'),
  (123, '', '', 'Triple', 'Not Booked'),
  (124, '', '', 'Quad', 'Not Booked'),
  (125, '', '', 'Queen', 'Not Booked'),
  (126, '', '', 'King', 'Not Booked'),
  (127, '', '', 'Twin', 'Not Booked'),
  (128, '', '', 'Hollywood Twin', 'Not Booked'),
  (129, '', '', 'Double-Double', 'Not Booked'),
  (130, '', '', 'Studio', 'Not Booked'),
  (131, '', '', 'Standard', 'Not Booked'),
  (132, '', '', 'Deluxe', 'Not Booked'),
  (133, '', '', 'Joint', 'Not Booked'),
  (134, '', '', 'Connecting', 'Not Booked'),
  (135, '', '', 'Suite', 'Not Booked'),
  (136, '', '', 'Standard', 'Not Booked'),
  (137, '', '', 'Apartment-Style', 'Not Booked'),
  (138, '', '', 'Accessible', 'Not Booked'),
  (139, '', '', 'Cabana', 'Not Booked'),
  (140, '', '', 'Villa', 'Not Booked'),
  (141, '', '', 'Single', 'Not Booked'),
  (142, '', '', 'Double', 'Not Booked'),
  (143, '', '', 'Triple', 'Not Booked'),
  (144, '', '', 'Quad', 'Not Booked'),
  (145, '', '', 'Queen', 'Not Booked'),
  (146, '', '', 'King', 'Not Booked'),
  (147, '', '', 'Twin', 'Not Booked'),
  (148, '', '', 'Hollywood Twin', 'Not Booked'),
  (149, '', '', 'Double-Double', 'Not Booked'),
  (150, '', '', 'Studio', 'Not Booked'),
  (151, '', '', 'Standard', 'Not Booked'),
  (152, '', '', 'Deluxe', 'Not Booked'),
  (153, '', '', 'Joint', 'Not Booked'),
  (154, '', '', 'Connecting', 'Not Booked'),
  (155, '', '', 'Suite', 'Not Booked'),
  (156, '', '', 'Standard', 'Not Booked'),
  (157, '', '', 'Apartment-Style', 'Not Booked'),
  (158, '', '', 'Accessible', 'Not Booked'),
  (159, '', '', 'Cabana', 'Not Booked'),
  (160, '', '', 'Villa', 'Not Booked');


  INSERT INTO roomcategory (CategoryDescription, CategoryName, Price)
VALUES
  ('Assigned to one person or a couple. Bed size varies.', 'Single', 1000),
  ('Assigned to two people with one double or two twin beds.', 'Double', 2000),
  ('Equipped for three people with various bed combinations.', 'Triple', 3000),
  ('Set up for four people with two double beds or bunk beds.', 'Quad', 4000),
  ('Queen room with a queen-sized bed.', 'Queen', 1000),
  ('King room with a king-sized bed.', 'King', 1000),
  ('Twin room with two twin-sized beds.', 'Twin', 2000),
  ('Hollywood twin room with two twin beds joined by the same headboard.', 'Hollywood Twin', 2000),
  ('Two double beds (or two queen beds) for 2-4 people.', 'Double Double', 3000),
  ('Studio room with a studio bed or additional beds. May have a kitchenette.', 'Studio', 4000),
  ('Same as a queen or single room, great for solo or couple travelers.', 'Standard', 5000),
  ('Slightly bigger with upgraded amenities or a nicer view.', 'Deluxe', 6000),
  ('Two rooms with a common wall but no connecting door.', 'Joint', 5000),
  ('Rooms with a connecting door for families or groups.', 'Connecting', 7000),
  ('Various sizes including basic, mini, and presidential suites.', 'Suite', 5000),
  ('Rooms with full kitchens and amenities for long stays.', 'Apartment Style', 6000),
  ('Handicapped-accessible rooms with wheelchair space.', 'Accessible', 5000),
  ('Rooms opening onto the swimming pool or with a private pool.', 'Cabana', 8000),
  ('Stand-alone houses with extra space, multiple bedrooms, and amenities.', 'Villa', 9000),
  ('Exclusive top-floor penthouse suites with luxury amenities.', 'Penthouse', 10000);
